-- nvim/colors/ubesluttsom.lua
-- Custom Neovim colorscheme based on 'dim.vim' with personal modifications

vim.cmd [[
  highlight clear
  syntax reset
]]

local colors_name = "ubesluttsom"
vim.g.colors_name = colors_name

local function set_highlights()
    vim.api.nvim_set_hl(0, 'Comment',                { cterm = { italic = true },    ctermfg = 8,    ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'Constant',               { cterm = nil,                  ctermfg = 1,    ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'CursorColumn',           { cterm = nil,                  ctermfg = 0,    ctermbg = 234, })
    vim.api.nvim_set_hl(0, 'CursorLine',             { cterm = nil,                  ctermfg = nil,  ctermbg = 234, })
    vim.api.nvim_set_hl(0, 'CursorLineNr',           { cterm = nil,                  ctermfg = 8,    ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'DiagnosticError',        { cterm = nil,                  ctermfg = 1,    ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'DiagnosticHint',         { cterm = nil,                  ctermfg = 7,    ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'DiagnosticInfo',         { cterm = nil,                  ctermfg = 4,    ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'DiagnosticOk',           { cterm = nil,                  ctermfg = 10,   ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'DiagnosticWarn',         { cterm = nil,                  ctermfg = 3,    ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'DiffAdd',                { cterm = nil,                  ctermfg = 16,   ctermbg = 22,  })
    vim.api.nvim_set_hl(0, 'DiffChange',             { cterm = nil,                  ctermfg = 16,   ctermbg = 94,  })
    vim.api.nvim_set_hl(0, 'DiffDelete',             { cterm = { bold = true },      ctermfg = 52,   ctermbg = 52,  })
    vim.api.nvim_set_hl(0, 'DiffText',               { cterm = { bold = true },      ctermfg = 0,    ctermbg = 11,  })
    vim.api.nvim_set_hl(0, 'Directory',              { cterm = nil,                  ctermfg = 4,    ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'Error',                  { cterm = nil,                  ctermfg = 160,  ctermbg = 0,   })
    vim.api.nvim_set_hl(0, 'ErrorMsg',               { cterm = nil,                  ctermfg = 15,   ctermbg = 1,   })
    vim.api.nvim_set_hl(0, 'FloatermBorder',         { cterm = nil,                  ctermfg = 236,  ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'Folded',                 { cterm = nil,                  ctermfg = nil,  ctermbg = 236, })
    vim.api.nvim_set_hl(0, 'FoldColumn',             { cterm = nil,                  ctermfg = 236,  ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'Function',               { cterm = { italic = true },    ctermfg = 14,   ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'GitGutterAdd',           { cterm = nil,                  ctermfg = 22,   ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'GitGutterChange',        { cterm = nil,                  ctermfg = 94,   ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'GitGutterDelete',        { cterm = nil,                  ctermfg = 52,   ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'Identifier',             { cterm = nil,                  ctermfg = 6,    ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'Ignore',                 { cterm = nil,                  ctermfg = 15,   ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'IncSearch',              { cterm = { reverse = true },   ctermfg = nil,  ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'LineNr',                 { cterm = nil,                  ctermfg = 236,  ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'MatchParen',             { cterm = { underline = true }, ctermfg = nil,  ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'ModeMsg',                { cterm = { bold = true },      ctermfg = nil,  ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'MoreMsg',                { cterm = nil,                  ctermfg = 2,    ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'NonText',                { cterm = nil,                  ctermfg = 236,  ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'Normal',                 { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'NormalFloat',            { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'Pmenu',                  { cterm = nil,                  ctermfg = 15,   ctermbg = 8,   })
    vim.api.nvim_set_hl(0, 'PmenuSbar',              { cterm = nil,                  ctermfg = nil,  ctermbg = 8,   })
    vim.api.nvim_set_hl(0, 'PmenuSel',               { cterm = nil,                  ctermfg = 8,    ctermbg = 15,  })
    vim.api.nvim_set_hl(0, 'PmenuThumb',             { cterm = nil,                  ctermfg = nil,  ctermbg = 0,   })
    vim.api.nvim_set_hl(0, 'PreProc',                { cterm = nil,                  ctermfg = 5,    ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'Question',               { cterm = nil,                  ctermfg = 2,    ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'Search',                 { cterm = nil,                  ctermfg = 0,    ctermbg = 11,  })
    vim.api.nvim_set_hl(0, 'SignColumn',             { cterm = nil,                  ctermfg = 236,  ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'Special',                { cterm = nil,                  ctermfg = 5,    ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'SpecialKey',             { cterm = nil,                  ctermfg = 4,    ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'SpellBad',               { cterm = { undercurl = true }, ctermfg = 9,    ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'SpellCap',               { cterm = { undercurl = true }, ctermfg = 10,   ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'SpellLocal',             { cterm = nil,                  ctermfg = nil,  ctermbg = 14,  })
    vim.api.nvim_set_hl(0, 'SpellRare',              { cterm = nil,                  ctermfg = nil,  ctermbg = 13,  })
    vim.api.nvim_set_hl(0, 'Statement',              { cterm = { bold = true },      ctermfg = 3,    ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'StatusLine',             { cterm = { italic = true },    ctermfg = 236,  ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'StatusLineNC',           { cterm = nil,                  ctermfg = 236,  ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'TabLine',                { cterm = nil,                  ctermfg = 236,  ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'TabLineFill',            { cterm = nil,                  ctermfg = 236,  ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'TabLineSel',             { cterm = { italic = true },    ctermfg = 236,  ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'TermCursor',             { cterm = { reverse = true },   ctermfg = nil,  ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'Todo',                   { cterm = nil,                  ctermfg = 0,    ctermbg = 11,  })
    vim.api.nvim_set_hl(0, 'Type',                   { cterm = nil,                  ctermfg = 2,    ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'Underlined',             { cterm = { underline = true }, ctermfg = 5,    ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'VertSplit',              { cterm = nil,                  ctermfg = 236,  ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'Visual',                 { cterm = { reverse = true },   ctermfg = nil,  ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'WarningMsg',             { cterm = nil,                  ctermfg = 1,    ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'WildMenu',               { cterm = nil,                  ctermfg = 0,    ctermbg = 11,  })

    -- Plugins
    vim.api.nvim_set_hl(0, 'Twilight',               { cterm = nil,                  ctermfg = 238,  ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'TelescopeBorder',        { cterm = nil,                  ctermfg = 236,  ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'TelescopeNormal',        { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'TelescopePromptNormal',  { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'TelescopePreviewNormal', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopeBorder', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopeMatching', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopeMultiIcon', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopeMultiSelection', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopeNormal', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopePreviewBlock', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopePreviewBorder', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopePreviewCharDev', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopePreviewHyphen', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopePreviewLine', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopePreviewLink', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopePreviewMatch', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopePreviewMessage', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopePreviewMessageFillchar', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopePreviewNormal', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopePreviewPipe', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopePreviewSocket', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopePreviewSticky', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopePreviewTitle', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopePreviewDirectory', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopePreviewWrite',   { cterm = nil,                  ctermfg = 8,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopePreviewRead',    { cterm = nil,                  ctermfg = 8,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopePreviewExecute', { cterm = nil,                  ctermfg = 8,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopePreviewUser',    { cterm = nil,                  ctermfg = 8,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopePreviewGroup',   { cterm = nil,                  ctermfg = 8,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopePreviewSize',    { cterm = nil,                  ctermfg = 8,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopePreviewDate',    { cterm = nil,                  ctermfg = 8,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopePromptBorder', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopePromptCounter', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopePromptNormal', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopePromptPrefix', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopePromptTitle', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopeResultsBorder', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopeResultsClass', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopeResultsComment', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopeResultsComment', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopeResultsConstant', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'TelescopeResultsDiffAdd',       { cterm = nil,                  ctermfg = 22,  ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'TelescopeResultsDiffChange',    { cterm = nil,                  ctermfg = 94,  ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'TelescopeResultsDiffDelete',    { cterm = nil,                  ctermfg = 52,  ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'TelescopeResultsDiffUntracked', { cterm = nil,                  ctermfg = 8,  ctermbg = nil, })
    vim.api.nvim_set_hl(0, 'TelescopeResultsField',         { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopeResultsFunction', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopeResultsIdentifier', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopeResultsLineNr', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopeResultsMethod', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopeResultsNormal', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopeResultsNumber', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopeResultsOperator', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopeResultsSpecialComment', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopeResultsStruct', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopeResultsTitle', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopeResultsVariable', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopeSelection', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopeSelectionCaret', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })
    -- vim.api.nvim_set_hl(0, 'TelescopeTitle', { cterm = nil,                  ctermfg = nil,  ctermbg = nil, })

    -- Cleared
    vim.api.nvim_set_hl(0, 'Conceal',                { nil, })
    vim.api.nvim_set_hl(0, 'TermCursorNC',           { nil, })
    vim.api.nvim_set_hl(0, 'Title',                  { nil, })
    vim.api.nvim_set_hl(0, 'VisualNC',               { nil, })

    -- Links
    vim.api.nvim_set_hl(0, 'CurSearch',              { link = 'Search' })
    vim.api.nvim_set_hl(0, 'CursorLineFold',         { link = 'FoldColumn' })
    vim.api.nvim_set_hl(0, 'CursorLineSign',         { link = 'SignColumn' })
    vim.api.nvim_set_hl(0, 'EndOfBuffer',            { link = 'NonText' })
    vim.api.nvim_set_hl(0, 'FloatBorder',            { link = 'VertSplit' })
    vim.api.nvim_set_hl(0, 'LineNrAbove',            { link = 'LineNr' })
    vim.api.nvim_set_hl(0, 'LineNrBelow',            { link = 'LineNr' })
    vim.api.nvim_set_hl(0, 'NonText',                { link = 'LineNr' })
    vim.api.nvim_set_hl(0, 'PmenuExtra',             { link = 'Pmenu' })
    vim.api.nvim_set_hl(0, 'PmenuExtraSel',          { link = 'PmenuSel' })
    vim.api.nvim_set_hl(0, 'PmenuKind',              { link = 'Pmenu' })
    vim.api.nvim_set_hl(0, 'PmenuKindSel',           { link = 'PmenuSel' })
    vim.api.nvim_set_hl(0, 'WinSeparator',           { link = 'VertSplit' })


    -- These need vimscript, apparently.
    vim.cmd('hi DiagnosticUnderlineError cterm=undercurl')
    vim.cmd('hi DiagnosticUnderlineWarn  cterm=underdashed')
    vim.cmd('hi DiagnosticUnderlineInfo  cterm=underdashed')
    vim.cmd('hi DiagnosticUnderlineHint  cterm=underdotted')
    vim.cmd('hi DiagnosticUnderlineOk    cterm=underdouble')
    -- vim.cmd('hi Comment                  cterm=none ctermfg=8 ctermbg=none')
end

-- Apply the highlights
set_highlights()
